services:
  - type: web
    name: mamafood-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mamafood-db
          property: connectionString
      - key: VAPID_PUBLIC
        sync: false
      - key: VAPID_PRIVATE
        sync: false

databases:
  - name: mamafood-db
    plan: free
    databaseName: mamafood
    user: mamafood_user

